list:
  KEYCLOAK_BACKBASE_EVENT_LISTENERS_AUDIT_INTEGRATIONSERVICEURL: "http://host.docker.internal:8092/audit-service"
  KEYCLOAK_BACKBASE_DEVICE_URL: "http://host.docker.internal:8181/device-management-service"
  KEYCLOAK_BACKBASE_FIDO_URL: "http://host.docker.internal:8181/fido-service"
  KEYCLOAK_BACKBASE_OIDC_TOKEN_CONVERTER_URL: "http://host.docker.internal:8181/oidc-token-converter-service"
  QUARKUS_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/backbase_identity?useSSL=false"
  QUARKUS_DATASOURCE_USERNAME: "bbiam"
  QUARKUS_DATASOURCE_PASSWORD: "bb1am:PW"
  QUARKUS_DATASOURCE_DRIVER: "com.mysql.cj.jdbc.Driver"
  QUARKUS_LOG_FILE_ENABLE: "false"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KEYCLOAK_CONNECTIONSJPA_QUARKUS_INITIALIZEEMPTY: "true"
  KEYCLOAK_CONNECTIONSJPA_QUARKUS_MIGRATIONSTRATEGY: "update"
  ONESPAN_AUTH_INTEGRATION_SERVICE_BASE_URL: "http://host.docker.internal:8580/"
  JAVA_TOOL_OPTIONS: "-Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.action=import -Dkeycloak.profile.feature.upload_scripts=enabled -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  PASSCODE_LENGTH: "6"
  API_INGESTION_BASE_PATH: "http://host.docker.internal:9001"
  API_ACCESS_CONTROL_BASE_PATH: "http://host.docker.internal:8086/access-control"
  API_AUDIT_BASE_PATH: "http://host.docker.internal:8092/audit-service"
  CONNECTION_TIMEOUT_MS: "5000"
  CONNECTION_REQUEST_TIMEOUT_MS: "5000"
  SOCKET_TIMEOUT_MS: "30000"
